Backand
EnedsonGomes/exercicios-novos-titans pull request #23
Opened 2022-02-08 23:47 UTC by EnedsonGomes

2022-02-09 03:40 UTC, edmargomes requested changes

2022-02-09 03:40 UTC, edmargomes commented on php/exercicio4/index.php
> +//echo "<br/>";
Remover codigo comentado, não se manda codigo comentado para produção

2022-02-09 03:40 UTC, edmargomes commented on php/exercicio4/index.php
> +
Remover esses dois espaços

2022-02-09 03:40 UTC, edmargomes commented on php/exercicio4/index.php
> +    echo "Os três números na ordem decrescente é $num1, $num3 e $num2.";
Colocar a identação para os echos

2022-02-09 03:40 UTC, edmargomes commented on php/exercicio4/index.php
> +    </fieldset>
Tem arquivo a mais, se esse codigo existe aqui, pq tem o exercicio4.html exercicio4forntend. Remover tudo q não usa

2022-02-09 03:41 UTC, EnedsonGomes commented
PR 23 só pode ser aprovado depois que aprovar o PR 22 do card anterior NVT93

2022-02-09 03:54 UTC, EnedsonGomes commented on php/exercicio4/index.php
> +//echo "<br/>";
ok, deixei pra lembrar das falhas vou salvar em outro arquivo.

2022-02-09 03:57 UTC, EnedsonGomes commented on php/exercicio4/index.php
> +
ok

2022-02-09 03:57 UTC, EnedsonGomes commented on php/exercicio4/index.php
> +    echo "Os três números na ordem decrescente é $num1, $num3 e $num2.";
ok

2022-02-09 03:58 UTC, EnedsonGomes commented on php/exercicio4/index.php
> +    </fieldset>
ok

2022-02-10 02:35 UTC, edmargomes requested changes

2022-02-10 02:35 UTC, edmargomes commented on php/exercicio4/index.php
> +    echo "Os três números na ordem decrescente é $num1, $num3 e $num2.";
Faltou os tabs para os echos, se eles estão dentro do if, precisa irem mais para frente

2022-02-10 22:43 UTC, EnedsonGomes commented on php/exercicio4/index.php
> +    echo "Os três números na ordem decrescente é $num1, $num3 e $num2.";
https://github.com/EnedsonGomes/exercicios-novos-titans/pull/25

2022-02-10 22:44 UTC, EnedsonGomes commented on php/exercicio4/index.php
> +    echo "Os três números na ordem decrescente é $num1, $num3 e $num2.";
fiz a correçao no PR acima

2022-02-14 01:09 UTC, edmargomes approved these changes

2022-02-14 01:10 UTC, merged