Backandexercicio5
EnedsonGomes/exercicios-novos-titans pull request #26
Opened 2022-02-12 21:17 UTC by EnedsonGomes

so deve ser aprovado após aprovação do card NVT - 99

2022-02-14 01:52 UTC, edmargomes requested changes
As revisões de html ja fiz no outro PR. Aqui os html estão duplicados no index e no frontend q não deveria existir.

Lembrar também de remover codigo comentado no php

2022-02-14 01:52 UTC, edmargomes commented on php/exercicio5/index.php
> +    }
Isso tudo poderia ser somente um elseif

```
elseif ($num1===$num2 || $num1===$num3 || $num2===$num3) {
   echo "Triangulo Isoceles";
}

2022-02-14 19:39 UTC, EnedsonGomes commented on php/exercicio5/index.php
> +    }
ok

2022-02-15 00:05 UTC, edmargomes requested changes

2022-02-15 00:05 UTC, edmargomes commented on php/exercicio5/exercicio5frontend.php
>      <meta charset="utf-8"/>
esse arquivo php é desnecessario. remover

2022-02-15 22:27 UTC, edmargomes approved these changes

2022-02-15 22:27 UTC, merged