Exercicio4
EnedsonGomes/exercicios-novos-titans pull request #28
Opened 2022-02-15 22:47 UTC by EnedsonGomes

Renomeando arquivos e colocando enunciado dentro do html

2022-02-15 22:54 UTC, edmargomes requested changes

2022-02-15 22:54 UTC, edmargomes commented on php/exercicio4/exercicio4forntend.php
>           <link rel="stylesheet" type="text/css" href="estilo.css">
Remover esse arquivo, tem dois arquivo exercicio4

2022-02-15 22:57 UTC, EnedsonGomes commented on php/exercicio4/exercicio4forntend.php
>           <link rel="stylesheet" type="text/css" href="estilo.css">
ok. feito. Verifique por favor.

2022-02-16 17:36 UTC, edmargomes approved these changes

2022-02-16 17:36 UTC, merged